services: docker

before_install:
    - docker build -t openquake/qgis-server:3 -f Dockerfile . 

install:
    - docker run -d -v $(pwd)/test/data:/var/www/data -p 8010:80 --name qgis-server openquake/qgis-server:3

before_script:
    # Get the installed package for qgis-server
    - docker exec -ti qgis-server rpm -q qgis-server

script:
    - sleep 5 && curl -s 'http://localhost:8010/ogc/test_project?service=WMS&request=GetCapabilities' | grep -ivq exception
