version: '2'
services:
  nginx:
    # build: .
    image: "nginx"
    volumes:
     - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "127.0.0.1:8010:80"
    networks:
     - qgis-server-net
    restart: always
  qgis-server:
    # build: .
    image: "openquake/qgis-server:3"
    environment:
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: 4
    networks:
     - qgis-server-net
    volumes:
     - ./data:/var/www/data
    restart: always

networks:
  qgis-server-net:
